python poc.dataflow.templates/PocJSONProcessor.py `
  --project=sales-poc-465319 `
  --region=us-east1 `
  --runner=DataflowRunner `
  --input_subscription=projects/sales-poc-465319/subscriptions/external-topic-sub `
  --db_user=gcp-poc-mysql-db-user1 `
  --db_password=PocUser1@12345 `
  --db_name=gcp-poc-mysql-db1 `
  --db_instance_connection_name=sales-poc-465319:us-east1:gcp-poc-mysql-db `
  --temp_location=gs://poc-dataflow-runner-staging/temp `
  --staging_location=gs://poc-dataflow-runner-staging/staging `
  --requirements_file=poc.dataflow.templates/requirements.txt