name: Deploy Modular GCP Resources

on:
  push:
    paths:
      - 'core/**'
      - '.github/workflows/deploygcpmodule.yml'
    branches: [ main ]

jobs:
  terraform:
    name: Apply GCP Terraform Modules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        # Use Google Cloud Workload Identity Federation for secure authentication
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Initialize and Apply Core Terraform Storage State
        working-directory: core
        run: |
          terraform init
          terraform validate
          terraform plan 
          terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Initialize and Apply Cloud Storage
        working-directory: core/storage
        run: |
          terraform init
          terraform validate
          terraform plan -var-file=../terraform.tfvars
          terraform apply -auto-approve -var-file=../terraform.tfvars
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Initialize and Apply Pub/Sub
        working-directory: core/pubsub
        run: |
          terraform init
          terraform validate
          terraform plan -var-file=../terraform.tfvars
          terraform apply -auto-approve -var-file=../terraform.tfvars
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}