name: Deploy Resources to GCP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
defaults:
      run:
        working-directory: core

jobs:
  deploy-to-gcp:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: core
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve