name: Deploy Dataflow Flex Template

on:
  push:
    branches: [ "main" ]
    paths: 
     - '.github/workflows/**'
     - 'np/**'
  pull_request:
    branches: [ "main" ]
    paths: 
     - '.github/workflows/**'
     - 'np/**'

permissions:
      id-token: write  # Required for Google GitHub Actions authentication
      contents: write  # Allows reading repository contents
      checks: write
      pull-requests: write
      security-events: write
      actions: read
      issues: read

jobs:
  build-and-deploy:
    runs-on: [ubuntu-latest]
    
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Authenticate to Google Cloud
      id: "auth"
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Artifact Registry Auth  
      run: |
        gcloud auth configure-docker

    - name: Build Docker image
      run: |
        cd np/dataflow/templates/python-template
        docker build -t pubsub-to-cloudsql:latest .
        docker tag 'pubsub-to-cloudsql:latest' 'gcr.io/sales-poc-465319/pubsub-to-cloudsql:latest'
        docker push gcr.io/sales-poc-465319/pubsub-to-cloudsql:latest

    - name: Build POS Processor Flex Template Spec
      run: |
        cd np/dataflow/templates/pos-processor-template
        gcloud dataflow flex-template build gs://poc-df-flex-template/templates/pubsub-to-cloudsql-spec.json `
          --image gcr.io/sales-poc-465319/pubsub-to-cloudsql:latest `
          --sdk-language "PYTHON" `
          --metadata-file metadata.json `
          --setup-file=./setup_new.py 

    - name: Run POS Processor Flex Template 1
      run: |
        gcloud dataflow flex-template run "pubsub-to-cloudsql-job-1" `
        --template-file-gcs-location=gs://poc-df-flex-template/templates/pubsub-to-cloudsql-spec.json `
        --region=us-east1 `
        --parameters="input_subscription=projects/sales-poc-465319/subscriptions/external-topic-df-sub,db_username=gcp-poc-mysql-db-user1,db_password=PocUser1@12345,db_name=gcp-poc-mysql-db1,db_instance_connection_name=sales-poc-465319:us-east1:gcp-poc-mysql-db" `
        --staging-location=gs://poc-df-flex-template/staging `
        --temp-location=gs://poc-df-flex-template/temp
