name: 'PubSub GCP Deploy'

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the 'main' branch

jobs:

  create-pubsub-topic_new:
    name: 'Create Pub/Sub Topic'
    runs-on: ubuntu-latest
    steps:
      
      - name: Setup GCP Service Account
        uses: 'google-github-actions/auth@v2'
        with:
           credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}          

      - name: Check and Create Pub/Sub topic
        run: |
          if ! gcloud pubsub topics describe weather-topic > /dev/null 2>&1; then
            gcloud pubsub topics create ace-json-topic
            echo "Topic 'ace-json-topic' created."
          else
            echo "Topic 'ace-json-topic' already exists."
          fi
        shell: bash
        env:
          CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
          CLOUDSDK_METRICS_ENVIRONMENT_VERSION: 2.1.0