name: 'Terraform GCP Deploy'

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the 'main' branch

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
       

  create-pubsub-topic_new:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
  
      - name: Setup GCP Service Account
        uses: 'google-github-actions/auth@v2'
        with:
           credentials_json: ${{ secrets.GCP_ACCOUNT_KEY }}          

      - name: Check and Create Pub/Sub topic
        run: |
          if ! gcloud pubsub topics describe weather-topic > /dev/null 2>&1; then
            gcloud pubsub topics create ace-json-topic
            echo "Topic 'ace-json-topic' created."
          else
            echo "Topic 'ace-json-topic' already exists."
          fi
        shell: bash
        env:
          CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
          CLOUDSDK_METRICS_ENVIRONMENT_VERSION: 2.1.0