name: 'Terraform GCP Deploy'

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the 'main' branch

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
       
    steps:
    # Use Google Cloud Workload Identity Federation for secure authentication
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Terraform Init
      run: terraform init
      env: 
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Terraform Format
      run: terraform fmt -check
      env: 
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Terraform Validate
      run: terraform validate
      env: 
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      run: terraform plan -no-color
      env: 
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
      env: 
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      